bsize: 24
num_iters: 5000
eval_interval: 500

# optimizer
lr: 0.01
momentum: 0.9
weight_decay: 0.0005

# configurations
dataset_cfg:
    OfficeHome:
        name: OfficeHome
        path: /home/chu980802/data/OfficeHome
        num_classes: 65
        domains:
                - Art
                - Clipart
                - Product
                - RealWorld
        list:
            all: _list.txt
            3shot_train: _train_3.txt
            3shot_test: _test_3.txt
    Office31:
        name: Office31
        path: /home/chu980802/data/Office31
        num_classes: 31
        domains:
                - amazon
                - dslr
                - webcam